---

- name: Configuring R5
  hosts: R5
  connection: network_cli
  gather_facts: no

  tasks:

    - name: Assigning IP Address on R5
      ios_config:
        #save_when: modified
        parents: interface e0/1
        lines:
          - ip add 30.30.30.1 255.255.255.252
        after:
          - no shutdown

    - name: Configuring eBGP for on R5 with AS 200
      ios_bgp:
        config:
          bgp_as: 200
          log_neighbor_changes: True
          neighbors:
            - neighbor: 30.30.30.2
              remote_as: 100
              timers:
                keepalive: 60
                holdtime: 180
          networks:
            - prefix: 5.5.5.5
              masklen: 32
          address_family:
            - afi: ipv4
        operation: merge
        #save_when: modified

      register: output
    - name: Printing the output of R2
      debug: var=output
