---

- name: Configuring R2
  hosts: R2
  connection: network_cli
  gather_facts: no

  tasks:

    - name: Assigning IP Address on R2
      ios_config:
        #save_when: modified
        parents: interface e0/1
        lines:
          - ip add 10.10.10.1 255.255.255.252
        after:
          - no shutdown

    - name: Configuring EIGRP on R2
      ios_config:
        #save_when: modified
        parents: router eigrp 10
        lines:
          - network 10.10.10.0
          - no auto-summary

      register: output
    - name: Printing the output of R2
      debug: var=output

- name : Configuring R3
  hosts : R3
  connection: network_cli
  gather_facts: no

  tasks:

    - name: Assigning IP Address on R3
      ios_config:
        #save_when: modified
        parents: "interface {{ item.interface }}"
        lines:
          - "ip add {{ item.ip }} 255.255.255.252"
        after:
          - no shutdown

      loop:
        - { interface: e0/1, ip: 10.10.10.2}
        - { interface: e0/2, ip: 20.20.20.1}

    - name: Configuring EIGRP on R3
      ios_config:
         #save_when: modified
        parents: router eigrp 10
        lines:
          - network 20.20.20.0
          - network 10.10.10.0
          - no auto-summary

      register: output
    - name: Printing the output of R3
      debug: var=output


- name: Configuring R4
  hosts: R4
  connection: network_cli
  gather_facts: no

  tasks:

    - name: Assigning IP Address on R4
      ios_config:
        #save_when: modified
        parents: interface e0/1
        lines:
          - ip add 20.20.20.2 255.255.255.252
        after:
          - no shutdown

    - name: Configuring EIGRP on R4
      ios_config:
        #save_when: modified
        parents: router eigrp 10
        lines:
          - network 20.20.20.0
          - no auto-summary

      register: output
    - name: Printing the output of R4
      debug: var=output

- name: configuring R5
  hosts: R5
  connection: network_cli
  gather_facts: no

  tasks:

    - name: Assigning IP Address on R5
      ios_config:
        #save_when: modified
        parents: "interface {{ item.interface }}"
        lines:
          - "ip add {{ item.ip }} "
        after:
          - no shutdown

      loop:
        - { interface: e0/1, ip: 30.30.30.1 255.255.255.252}
        - { interface: loopback0, ip: 5.5.5.5 255.255.255.255}

    - name: Configuring eBGP for on R5 with AS 200
      ios_bgp:
        config:
          bgp_as: 200
          log_neighbor_changes: True
          neighbors:
            - neighbor: 30.30.30.2
              remote_as: 100
              timers:
                keepalive: 60
                holdtime: 180
          networks:
            - prefix: 5.5.5.5
              masklen: 32
          address_family:
            - afi: ipv4
        operation: merge
        #save_when: modified

      register: output
      
    - name: Printing the output of R2
      debug: var=output
